eesast/THUAI6

CAPI/proto/Message2Clients.grpc.pb.cc, CAPI/proto/Message2Clients.grpc.pb.h, CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, dependency/proto/Message2Clients.proto
=> chore: add receive message interface

.gitignore, CAPI/CMakeLists.txt
=> chore: add temp CMakeLists

CAPI/API/include/API.h, CAPI/API/include/structures.h, CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, dependency/proto/Message2Clients.proto
=> chore: add structures.h and API.h

CAPI/API/include/AI.h, CAPI/API/include/constants.h, CAPI/API/include/logic.h, CAPI/API/include/state.h, CAPI/API/src/AI.cpp, CAPI/API/src/logic.cpp, CAPI/CMakeLists.txt
=> feat: ✨ build basic code structure

CAPI/API/include/AI.h, CAPI/API/include/API.h
=> fix: :bug: fix some bugs

CAPI/API/include/AI.h, CAPI/API/include/API.h, CAPI/API/src/AI.cpp
为了保证代码的复用性、放弃了API部分人类和屠夫分开使用两种接口，转而所有函数都声明在IAPI类里，不希望被调用的函数直接定义为空。
否则，可能会有类似于
IAPI->(IHumanAPI,IButcherAPI)->(IHumanAPIForLogic,IButcherAPIForLogic)->具体实现
这样的代码，这并不合理。
=> refactor: 🎨 change api structure 

logic/Client/StatusBarOfCircumstance.xaml, logic/Client/StatusBarOfHunter.xaml
=> chore: choose some cuter emojis

CAPI/API/include/API.h, CAPI/API/include/logic.h, CAPI/API/include/state.h, CAPI/API/include/utils.hpp, CAPI/API/src/logic.cpp, CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, dependency/proto/Message2Clients.proto
=> feat(CAPI): ✨ add reading message2clients

CAPI/API/include/API.h, CAPI/API/include/logic.h, CAPI/API/include/state.h, CAPI/API/include/structures.h, CAPI/API/include/utils.hpp, CAPI/API/src/logic.cpp, CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, dependency/proto/Message2Clients.proto
=> feat(CAPI): ✨ finish some of the 1-1 rpc service

CAPI/API/include/API.h, CAPI/API/include/Communication.h, CAPI/API/include/logic.h, CAPI/API/src/API.cpp, CAPI/API/src/Communication.cpp, CAPI/API/src/logic.cpp
=> refactor(CAPI): :art: unbind  logic and communication

CAPI/API/include/API.h, CAPI/API/src/API.cpp
=> feat: make defination of some functions in API

CAPI/API/include/API.h
=> fix(CAPI): 🐛 fix multi definition

CAPI/API/include/API.h, CAPI/API/include/Communication.h, CAPI/API/include/logic.h, CAPI/API/include/utils.hpp, CAPI/API/src/API.cpp, CAPI/API/src/Communication.cpp, CAPI/API/src/logic.cpp, CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, CAPI/proto/MessageType.pb.cc, CAPI/proto/MessageType.pb.h, CAPI/proto/Services.grpc.pb.cc, CAPI/proto/Services.grpc.pb.h, CAPI/proto/Services.pb.cc, dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto, dependency/proto/Services.proto
[feat(CAPI): ✨ complete most communication functions, test required
=> feat(CAPI): ✨ complete most communication functions, test required

CAPI/API/include/API.h
=> feat: add human status enum

CAPI/API/include/structures.h, CAPI/API/include/utils.hpp, CAPI/proto/Services.grpc.pb.cc, CAPI/proto/Services.grpc.pb.h, CAPI/proto/Services.pb.cc, dependency/proto/Services.proto
=> fix(proto): :bug: fix wrong service name

installer/Installer/Installer.csproj, installer/Installer/Model.cs
- [ √] 您的代码是否能够编译通过？
- [ √] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI6/pulls) 中是否有与你的贡献功能相同的更改？
- [ √] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI6/blob/dev/CODE_OF_CONDUCT.md)？
- [ √] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI6#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> fix: fix some compile bugs

CAPI/API/include/API.h, CAPI/API/include/Communication.h, CAPI/API/include/logic.h, CAPI/API/src/AI.cpp, CAPI/API/src/API.cpp, CAPI/API/src/Communication.cpp, CAPI/API/src/logic.cpp, CAPI/API/src/main.cpp
=> refactor(CAPI): :zap: change save human/fix machine logic

logic/Server/Game.cs, logic/Server/GameServer.cs, logic/logic.sln
=> chore: add move function

CAPI/API/include/API.h, CAPI/API/include/logic.h, CAPI/API/src/AI.cpp, CAPI/API/src/API.cpp, CAPI/API/src/Communication.cpp, CAPI/API/src/DebugAPI.cpp, CAPI/API/src/logic.cpp, CAPI/API/src/main.cpp
=> feat(CAPI): :sparkles: complete temp debug api

CAPI/API/include/Communication.h, CAPI/API/include/logic.h, CAPI/API/src/Communication.cpp, CAPI/API/src/logic.cpp
=> refactor(CAPI): :sparkles: remake reading message

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> chore: designed new gui for editing configuration

CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, CAPI/proto/MessageType.pb.cc, CAPI/proto/MessageType.pb.h, dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto
=> feat(proto): :sparkles: add game state enum

CAPI/API/include/API.h, CAPI/API/include/logic.h, CAPI/API/include/structures.h, CAPI/API/include/utils.hpp, CAPI/API/src/API.cpp, CAPI/API/src/DebugAPI.cpp, CAPI/API/src/logic.cpp
=> feat(CAPI): :sparkles: complete basic logic

dependency/proto/MessageType.proto, logic/GameClass/GameObj/Character/Character.SkillManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Gaming/PropManager.cs, logic/Gaming/SkillManager.cs, logic/Preparation/Interface/ICharacter.cs, logic/Preparation/Utility/EnumType.cs
- [*] 您的代码是否能够编译通过？
- [*] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI6/blob/dev/CODE_OF_CONDUCT.md)？
- [*] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI6#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> feat: Add  Gaming managers

CAPI/API/include/API.h, CAPI/API/include/logic.h, CAPI/API/src/DebugAPI.cpp, CAPI/API/src/logic.cpp, CAPI/API/src/main.cpp
=> feat(CAPI): :loud_sound: add debug api logger

CAPI/API/include/API.h, CAPI/API/include/utils.hpp, CAPI/API/src/AI.cpp, CAPI/API/src/API.cpp, CAPI/API/src/DebugAPI.cpp
=> feat(CAPI): :sparkles: add debug api timer

CAPI/API/src/DebugAPI.cpp
=> feat(CAPI): :sparkles: add api warn logger

CAPI/API/include/AI.h, CAPI/API/include/API.h, CAPI/API/include/structures.h, CAPI/API/src/DebugAPI.cpp, CAPI/API/src/logic.cpp, CAPI/API/src/main.cpp
=> feat(CAPI): ✨ add print info, and fix some bug

CAPI/API/include/API.h, CAPI/API/src/API.cpp, CAPI/API/src/DebugAPI.cpp
=> style(CAPI): 🎨 change some different naming styles

CAPI/API/include/Communication.h, CAPI/API/include/logic.h, CAPI/API/src/Communication.cpp, CAPI/API/src/logic.cpp
=> perf(CAPI): :lock: fix busy waiting

CAPI/API/include/utils.hpp, CAPI/API/src/logic.cpp, PyAPI/PyAPI/AI.py, PyAPI/PyAPI/DebugAPI.py, PyAPI/PyAPI/logic.py, PyAPI/PyAPI/utils.py, PyAPI/requirements.txt
=> refactor(API): :art: add HaveView function

CAPI/API/include/AI.h, CAPI/API/include/API.h, CAPI/API/include/Communication.h, CAPI/API/include/constants.h, CAPI/API/include/logic.h, CAPI/API/include/state.h, CAPI/API/include/structures.h, CAPI/API/include/utils.hpp, CAPI/API/src/AI.cpp, CAPI/API/src/API.cpp, CAPI/API/src/Communication.cpp, CAPI/API/src/DebugAPI.cpp, CAPI/API/src/logic.cpp, CAPI/API/src/main.cpp
=> refactor(CAPI): :art: affect proto rename to capi

CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, CAPI/proto/MessageType.pb.cc, CAPI/proto/MessageType.pb.h, dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto
=> feat(proto): :sparkles: update with new rules

CAPI/proto/Message2Clients.pb.cc, CAPI/proto/Message2Clients.pb.h, dependency/proto/Message2Clients.proto
=> feat(proto): 🎨 change type of team

CAPI/API/include/state.h, CAPI/API/include/structures.h, CAPI/API/include/utils.hpp, CAPI/API/src/logic.cpp
=> feat(CAPI): ✨ change have view func, add bullet

logic/GameClass/GameObj/Character/Character.Ghost.cs, logic/GameClass/GameObj/Character/Character.SkillManager.cs, logic/GameClass/GameObj/Character/Character.Student.cs, logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Preparation/Utility/GameData.cs, logic/Server/CopyInfo.cs
=> fix: the bug of occupation initialzation

dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto
=> feat(proto): ✨ add message of all

logic/Client/MainWindow.xaml.cs, logic/Client/StatusBarOfCircumstance.xaml, logic/Client/StatusBarOfCircumstance.xaml.cs, logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml.cs, logic/GameClass/GameObj/Character/Character.SkillManager.cs, logic/Server/CopyInfo.cs
=> fit proto files and change the status bar of circumstance 

CAPI/proto/Services.pb.cc, dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto
=> feat(proto): :sparkles: update proto

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp
=> feat(CAPI): :sparkles: update new services

logic/Server/GameServer.cs
=> fix: fix StartLearning fuction

logic/Gaming/Game.cs, logic/Server/CopyInfo.cs, logic/Server/GameServer.cs, logic/Server/HttpSender.cs, logic/Server/Server.csproj
=> feat: add TeamCommunication

dependency/proto/Message2Clients.proto, dependency/proto/MessageType.proto, logic/Client/MainWindow.xaml.cs, logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml, logic/Client/StatusBarOfSurvivor.xaml.cs, logic/GameClass/GameObj/Character/Character.Skill.cs
change the status bar of student and fit the  new protos
=> feat: :sparkles: change the status bar of student

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/state.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/proto/Message2Clients.pb.cc, CAPI/cpp/proto/Message2Clients.pb.h, CAPI/cpp/proto/Message2Server.pb.cc, CAPI/cpp/proto/Message2Server.pb.h, CAPI/cpp/proto/Services.grpc.pb.cc, CAPI/cpp/proto/Services.grpc.pb.h, CAPI/cpp/proto/Services.pb.cc
=> feat(CAPI): :sparkles: update with new rules

dependency/proto/Message2Clients.proto, dependency/proto/Services.proto
=> feat(proto): 🎨 change map reading

logic/Client/MainWindow.xaml.cs
=> feat: :art: finish the keyboard control

logic/Client/Client.csproj, logic/Client/CommandLineArgs.cs, logic/Client/MainWindow.xaml.cs, logic/Client/PlaybackClient.cs
almost accomplish the function of client
=> feat: :sparkles: almost accomplish the function of Client

dependency/proto/Message2Server.proto, dependency/proto/Services.proto, dependency/proto/py_output.sh
=> feat(proto): ✨ add treat msg

logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/Character/Skill.cs, logic/Gaming/Game.cs, logic/Gaming/PropManager.cs, logic/Preparation/Interface/IOccupation.cs, logic/Preparation/Utility/EnumType.cs, logic/Server/CopyInfo.cs
=> refactor: :art: help Server

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> Chore: GUI Update

logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/Game.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs
=> make Treat and Rescue have default way

dependency/proto/Services.proto, logic/Client/CommandLineArgs.cs, logic/Client/MainWindow.xaml.cs, logic/Client/Properties/launchSettings.json, logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml.cs, logic/Server/CopyInfo.cs, logic/Server/GameServer.cs, logic/Server/Properties/launchSettings.json, logic/cmd/gameServer.cmd
fix some bugs due to copy error
=> fix: :bug: fix some bugs due to the copy errors

logic/Server/ArgumentOption.cs, logic/Server/GameServer.cs
=> fix: 🐛 fix some rpc services and argument options

logic/GameClass/GameObj/Character/Skill.cs, logic/Gaming/AttackManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Preparation/Interface/IOccupation.cs, logic/Preparation/Utility/EnumType.cs, logic/Preparation/Utility/GameData.cs, logic/cmd/gameServer.cmd, logic/规则Logic.md
=> fix: 🚑 make the bullet to the right position

logic/GameClass/GameObj/Character/Character.cs, logic/Gaming/Game.cs, logic/Gaming/PropManager.cs
=> feat: ✨ support UseProp and ThrowProp by default

logic/Client/MainWindow.xaml.cs, logic/Server/ArgumentOption.cs, logic/Server/GameServer.cs, logic/cmd/gameServer.cmd
=> chore:improve the keyboard control to use/pick/throw props

logic/Server/GameServer.cs, logic/Server/Properties/launchSettings.json, logic/cmd/gameServer.cmd
=> fix: :bug: fix the bug of command line

installer/Installer/MainWindow.xaml, installer/Installer/MainWindow.xaml.cs, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> Chore: Bug Fixes

logic/ClientTest/Program.cs, logic/Server/ArgumentOption.cs, logic/Server/GameServer.cs, logic/Server/Properties/launchSettings.json, logic/cmd/gameServer.cmd
=> feat: 🎨 improve argument options

installer/Installer/Model.cs
=> Chore: Fix json cannot close bug

dependency/proto/Message2Clients.proto
=> feat(proto): :fire: remove some message

CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/API/src/main.cpp
=> refactor(CAPI): :sparkles: change view function

logic/Gaming/ActionManager.cs, logic/cmd/gameServer.cmd
=> fix: 🚑 fix the fuction of treating

logic/Server/GameServer.cs, logic/Server/Server.csproj
=> fix: :bug: fix the conflict of EnumType

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/AI.cpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/State.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/main.py, CAPI/python/PyAPI/structures.py, CAPI/python/PyAPI/utils.py, CAPI/python/run.sh
=> feat(CAPI): ✨ complete python interface and fix various of bugs

logic/Server/CopyInfo.cs, logic/Server/GameServer.cs
=> fix: fix bugs of Playback and MessageToClient and fix problem of calling AllPlayerUsePassiveSkill

dependency/proto/MessageType.proto, logic/Client/MainWindow.xaml.cs, logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml.cs, logic/GameClass/GameObj/Character/Character.BuffManager.cs, logic/GameClass/GameObj/Character/Character.cs, logic/Preparation/Utility/EnumType.cs, logic/Server/CopyInfo.cs
name the new character/bullet/buff
=> refactor: :rocket: name the new buff/character/bullet

logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/Map/Door.cs, logic/Gaming/Game.cs, logic/Server/GameServer.cs
=> fix: 🐛 help Client get CD

logic/GameClass/GameObj/Character/Skill.cs
=> fix: 🐛 fix the bug about Client Skill CD

logic/Client/MainWindow.xaml.cs, logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml.cs
=> fix: Make the cooling time and the position of characters correct 

logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/Map/Window.cs, logic/Gaming/ActionManager.cs, logic/Preparation/Interface/IOccupation.cs, logic/Preparation/Utility/GameData.cs, logic/cmd/gameServer.cmd
=> fix: :bug: fix the bug about Lock the Door

logic/Client/MainWindow.xaml.cs, logic/Client/PlaybackClient.cs, logic/Client/Properties/launchSettings.json, logic/Server/Properties/launchSettings.json, logic/cmd/gameServer.cmd, logic/cmd/playback.cmd
=> fix: Redraw the bullets in the map

logic/Server/RpcServices.cs
=> fix: :bug: fix bugs of invaild num

logic/Server/GameServer.cs, logic/Server/RpcServices.cs
=> fix: :bug: fix bug of server exception

logic/GameClass/GameObj/Bullet/Bullet.Ghost.cs, logic/GameClass/GameObj/Character/Skill.cs, logic/GameClass/GameObj/Map/MapGameTimer.cs, logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager .cs, logic/Preparation/Interface/ITimer.cs, logic/Preparation/Utility/GameData.cs, logic/Server/GameServer.cs, logic/cmd/gameServer.cmd
=> build: :construction: adjust the Rescue mechanism

logic/GameClass/GameObj/Character/Skill.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager .cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Gaming/SkillManager/SkillManager.cs, logic/cmd/gameServer.cmd, logic/规则Logic.md
=> build: 📝 edit 规则Logic.md

installer/Installer/Common.cs, installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> Chore:PlayerNumber selection/remapped login gui

logic/Server/GameServer.cs, logic/Server/Program.cs, logic/Server/RpcServices.cs
=> refactor: :art: improve score function

logic/Server/GameServer.cs
=> fix: :bug: fix a terrible bug

installer/Installer/Common.cs, installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> chore: Using PasswordBox for password now

logic/Client/CommandLineArgs.cs, logic/Client/MainWindow.xaml.cs, logic/Client/PlaybackClient.cs, logic/Client/Properties/launchSettings.json, logic/Client/StatusBarOfCircumstance.xaml.cs, logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml.cs, logic/Server/GameServer.cs, logic/cmd/gameServer.cmd, logic/cmd/playback.cmd, playback/Playback/MessageReader.cs, playback/Playback/MessageWriter.cs
fix the bug due to 1024 * 1024
=> fix: :bug: fix the bug of message reader

logic/Client/MainWindow.xaml.cs, logic/Client/Properties/launchSettings.json, logic/Client/StatusBarOfCircumstance.xaml.cs, logic/Gaming/Game.cs, logic/Server/GameServer.cs, logic/Server/RpcServices.cs, logic/cmd/gameServer.cmd
=> improve the function when a spectator joins a game

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/main.py, CAPI/python/run.sh
=> feat(CAPI): ✨ add some missing interfaces

playback/Playback/MessageWriter.cs
=> fix: :zap: improve message writer

CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/logic.py
=> feat(CAPI): :sparkles: add clairaudience

CAPI/Tool_tutorial.md
=> feat(CAPI): :sparkles: add tool tutorial

CAPI/CAPI接口(cpp).md, CAPI/CAPI接口(python).md, CAPI/Tool_tutorial.md, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/proto/MessageType.pb.cc, CAPI/cpp/proto/MessageType.pb.h, CAPI/python/PyAPI/structures.py, CAPI/python/PyAPI/utils.py, CAPI/python/generate_proto.sh, dependency/proto/MessageType.proto, 使用文档.md
=> feat(proto): ✨ add sunshine

CAPI/cpp/API/include/state.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp
=> fix(CAPI): :pencil2: fix some missing headers

CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/logic.cpp
=> style(CAPI): :bug: fix some warnings

CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/main.cpp
=> fix: :bug: delete wrong cout

logic/Gaming/CharacterManager .cs
=> fix: 🐛 fix a bug about attacking the Robot

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> chore: independent download thread so ui can show "processing" correctly

logic/Client/MainWindow.xaml.cs, logic/Client/StatusBarOfCircumstance.xaml.cs, logic/cmd/playback.cmd
=> add the sign of playback to the GUI client

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
chore: updated upload interaction, now opens AI file in the pack as default
=> chore: updated deleteall function, now saving user's code;

CAPI/cpp/API/src/main.cpp
=> fix(CAPI): :bug: fix array out of range

使用文档.md
=> docs: :memo: change 使用文档.md

CAPI/cpp/API/include/constants.h, CAPI/python/PyAPI/constants.py
=> style(CAPI): :art: add space

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs, installer/InstallerUpdater/App.xaml, installer/InstallerUpdater/App.xaml.cs, installer/InstallerUpdater/AssemblyInfo.cs, installer/InstallerUpdater/InstallerUpdater.csproj, installer/InstallerUpdater/MainWindow.xaml, installer/InstallerUpdater/MainWindow.xaml.cs, installer/InstallerUpdater/Program.cs, installer/installer.sln
=> chore: now allows self update

.github/workflows/upload_deploy.yml
=> ci: :green_heart: fix CI

CAPI/cpp/API/include/API.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py
=> fix(CAPI): :bug: change async Wait to sync

.github/workflows/upload_deploy.yml
=> ci: 💚 try CI

.github/workflows/upload_deploy.yml
=> fix: 🐛 fix Ci

.github/workflows/upload_deploy.yml, logic/Preparation/Interface/IOccupation.cs
=> fix: 🚑 fix a bug about the Sunshine

.github/workflows/upload_COS.yml
=> ci: fix ci md2pdf

.github/workflows/upload_COS.yml
=> ci: 💚 fix CI

.github/workflows/upload_COS.yml
=> fix: :poop: fix CI

.github/workflows/upload_COS.yml, docs/CAPI接口（cpp）.md, docs/CAPI接口（python）.md
=> fix: 💩 fix CI

.github/workflows/upload_COS.yml
=> chore: 💩 fix Ci

CAPI/python/PyAPI/logic.py
=> fix(CAPI): ✏️ fix wrong return when not found

.github/workflows/upload_COS.yml, docs/CAPI接口（python）.md
=> chore: :rewind: return

.github/workflows/upload_COS.yml, dependency/py/HashFiles.py
=> fix: 💩 fix py

.github/workflows/upload_COS.yml
=> fix: 💚 fix CI

.github/workflows/upload_COS.yml, docs/使用文档.md
=> ci: :green_heart: add osx

CAPI/cpp/API/src/DebugAPI.cpp, CAPI/python/PyAPI/DebugAPI.py
=> fix(CAPI): :bug: fix wrong print format

CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/logic.py
=> fix(CAPI): 🐛 fix missing lock

docs/CAPI接口（cpp）.md, docs/CAPI接口（python）.md
=> docs: 📝 edit CAPI接口

logic/GameEngine/CollisionChecker.cs, logic/Preparation/Utility/XY.cs
=> refactor: :zap: Try to fix the problem about Moving

.github/workflows/upload_COS.yml, CAPI/cmd/RunServer.cmd, CAPI/shell/RunCpp.sh, CAPI/shell/RunPython.sh, docs/使用文档.md
=> docs: :memo: edit 使用文档.md

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs, installer/InstallerUpdater/MainWindow.xaml.cs, installer/InstallerUpdater/Program.cs
=> chore: bug fixes & now support OS selection

interface/Assets/Scripts/MapManager.cs, interface/Assets/Scripts/MessageReceiver.cs, interface/Assets/Scripts/Student.cs
=> feat(Scripts): ✨ add students' move

.github/workflows/upload_COS.yml, CAPI/cmd/RunPython.cmd, docs/使用文档.md
=> docs: 📝 edit RunPython.cmd

CAPI/cpp/API/src/AI.cpp, docs/使用文档.md
=> docs: 📝 edit 使用文档

logic/Client/Client.csproj, logic/Client/MainWindow.xaml.cs
=> chore: :sparkles: add eesast.ico to client.exe

CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/logic.py, CAPI/python/run.sh
=> refactor(CAPI): :poop: remake load buffer

docs/Tool_tutorial.md
=> docs: 📝 update fmt tutor

logic/Server/PlaybackServer.cs, logic/Server/Program.cs
=> feat: :art: add final score to playbackServer

.github/workflows/docker.yml
=> Chore: Fix some workflow bugs

CAPI/cpp/API/src/AI.cpp, logic/Client/MainWindow.xaml.cs, logic/cmd/playback.cmd
fix the bug caused by frequent refresh of map
=> fix: :bug: fix the bug caused by frequent refresh of map

.github/workflows/docker.yml, dependency/Dockerfile/Dockerfile_cpp, dependency/Dockerfile/Dockerfile_run, dependency/shell/cpp_output.sh, dependency/shell/generate_proto.sh
=> Chore: Change dockerfile

.github/workflows/docker.yml
=> Chore: change permission

.github/workflows/docker.yml, dependency/shell/run.sh
=> Chore: change run.sh

docs/CAPI接口（python）.md
=> doc: :bug: fix wrong python doc

dependency/Dockerfile/Dockerfile_cpp, dependency/Dockerfile/Dockerfile_run, dependency/Dockerfile/README.md
=> fix: fix docker run

dependency/shell/run.sh
=> chore: add docker params

dependency/Dockerfile/Dockerfile_base
=> Chore: rebuild dockerfile

dependency/shell/compile.sh
add file num to 5.
check file existence.
if cpp not exist, then check py, if py not exist either, compile failed.
=> build: :construction_worker: update compile.sh

CAPI/cpp/API/src/logic.cpp
=> fix(CAPI): 🐛 fix wrong gate view

CAPI/python/PyAPI/AI.py, CAPI/python/PyAPI/State.py, CAPI/python/PyAPI/structures.py, CAPI/python/PyAPI/utils.py, CAPI/python/run.sh
=> fix(CAPI): 🐛 fix wrong __init__

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/logic.py, CAPI/python/run.sh
=> feat(CAPI): :sparkles: add have view in capi

dependency/shell/run.sh
=> fix: add pb file in docker

dependency/shell/run.sh
=> fix: add busy waiting

dependency/shell/run.sh
=> fix: run main.py

docs/CAPI接口（cpp）.md, docs/CAPI接口（python）.md
=> docs: 📝 edit capi docs

.github/workflows/upload_COS.yml, logic/GameEngine/MoveEngine.cs
=> ci: :green_heart: Try to fix Hash

.github/workflows/upload_COS.yml, dependency/algorithm/README.md, dependency/shell/run.sh, docs/CAPI接口（cpp）.md, docs/CAPI接口（python）.md, logic/GameEngine/MoveEngine.cs
=> chore: add finish.lock in docker

.github/workflows/upload_COS.yml
=> fix: :bug: fix the storaged files

logic/Gaming/CharacterManager .cs
=> fix: ⏪ cancel removing the student

CAPI/python/PyAPI/constants.py, docs/使用文档.md
=> docs: 📝 fix constants.py

dependency/shell/run.sh
=> add result.json

dependency/shell/run.sh
=> chore: not allow spectator when running competitions

dependency/shell/run.sh, logic/Server/GameServer.cs, logic/Server/Properties/launchSettings.json
=> chore: add result file in docker

dependency/shell/run.sh
=> fix: grap json

dependency/shell/run.sh
=> chore: add finish when G

CAPI/python/PyAPI/constants.py
=> fix: fix constant.py

CAPI/cpp/API/include/logic.h, CAPI/cpp/API/src/logic.cpp, CAPI/python/PyAPI/logic.py, docs/CAPI接口（cpp）.md, docs/CAPI接口（python）.md
=> fix(CAPI): 🐛 fix various of bugs

CAPI/cpp/API/include/AI.h, CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/ConcurrentQueue.hpp, CAPI/cpp/API/include/constants.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/state.h, CAPI/cpp/API/include/structures.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/AI.cpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp, CAPI/cpp/API/src/main.cpp, CAPI/python/run.sh
=> fix(CAPI): :bug: fix windows get message define

dependency/shell/run.sh
=> chore: redirect err stream

CAPI/cpp/proto/Services.grpc.pb.h
=> fix(CAPI): :bug: fix missing undef

logic/Server/PlaybackServer.cs
=> fix: :bug: spectator now can get mapMsg when isgaming

dependency/shell/compile.sh, docs/Tool_tutorial.md, logic/Server/RpcServices.cs
=> fix: quit rpc when spectator exits

logic/Client/StatusBarOfHunter.xaml.cs, logic/Client/StatusBarOfSurvivor.xaml.cs
refresh the name of status to the current rule
=> fix: :bug: refresh the name of status to the current rule

installer/Installer/Common.cs, installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs, installer/InstallerUpdater/MainWindow.xaml, installer/InstallerUpdater/Program.cs
=> fix(client): :rotating_light: fix window size and remove compiler warnings

logic/Gaming/ActionManager.cs
=> fix: 💩 fix the bug temporarily

logic/Server/GameServer.cs, logic/Server/PlaybackServer.cs, logic/Server/Program.cs, logic/Server/RpcServices.cs, logic/Server/ServerBase.cs
=> refactor(server): :recycle: make server base class to unify gameserver and playback server

logic/Server/RpcServices.cs
=> chore: note when client exit

logic/Server/RpcServices.cs
=> feat: :zap: add binary message to SendMessage

logic/Server/GameServer.cs
=> fix: del send gameresult

docs/使用文档.md, logic/Client/MainWindow.xaml
=> feat(client): :sparkles: add hot key `F11` to maximize

logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager .cs
=> fix(logic): :rotating_light: remove compiler warnings

CAPI/cpp/API/src/logic.cpp, CAPI/cpp/API/src/main.cpp, dependency/py/rank.py
=> ci: ✨ add rank.py

CAPI/cpp/proto/Services.grpc.pb.h, dependency/shell/compile.sh
=> ci: ✨ compile python

CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/src/Communication.cpp, CAPI/cpp/proto/Services.grpc.pb.h, CAPI/python/PyAPI/API.py, CAPI/python/PyAPI/Communication.py, CAPI/python/PyAPI/DebugAPI.py, CAPI/python/PyAPI/Interface.py, CAPI/python/PyAPI/State.py, CAPI/python/PyAPI/constants.py, CAPI/python/PyAPI/logic.py, CAPI/python/PyAPI/main.py, CAPI/python/PyAPI/utils.py
=> fix: update Services.grpc.pb.h

CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/src/Communication.cpp, CAPI/python/PyAPI/Communication.py
=> feat(CAPI): :sparkles: add move limit

dependency/shell/compile.sh
=> fix: :bug: fix python compile fail

dependency/Dockerfile/Dockerfile_cpp, dependency/shell/py_output.sh, dependency/shell/run.sh
=> fix: :poop: fix python compile

dependency/Dockerfile/Dockerfile_cpp, dependency/shell/run.sh
=> chore: test send curl

dependency/shell/run.sh
=> chore: test send info in docker

logic/Server/GameServer.cs
=> chore: send game res on game end

installer/Installer/MainWindow.xaml, installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> chore: now shows "正在检查更新" when starting up

logic/Server/RpcServices.cs
=> feat: :sparkles: add SkillParam to UseSkill

logic/GameClass/GameObj/Bullet/Bullet.cs, logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/Map/Chest.cs, logic/GameClass/GameObj/Prop/Consumables.cs, logic/GameClass/GameObj/Prop/PickedProp.cs, logic/GameClass/GameObj/Prop/Prop.cs, logic/Gaming/ActionManager.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/PropManager.cs, logic/Preparation/Utility/EnumType.cs, logic/Preparation/Utility/GameData.cs, logic/Server/CopyInfo.cs
=> feat: :sparkles: add craftingBench and change Prop to consumables

dependency/shell/run.sh
=> chore: only send result in server

logic/Client/MainWindow.xaml.cs, logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/GameObj.cs, logic/GameClass/GameObj/Map/Door.cs, logic/GameClass/GameObj/Map/Map.cs, logic/GameClass/GameObj/Moveable.cs, logic/GameClass/GameObj/Prop/Gadget.cs, logic/GameClass/GameObj/Prop/Item.cs, logic/Gaming/ActionManager.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/PropManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Gaming/SkillManager/SkillManager.PassiveSkill.cs, logic/Preparation/Interface/IMoveable.cs, logic/Preparation/Interface/IOccupation.cs, logic/Preparation/Interface/ISkill.cs, logic/Preparation/Utility/GameData.cs, logic/Server/CopyInfo.cs
=> refactor: 🚧 refactor the skill fuction

logic/Server/GameServer.cs
=> chore: async send msg

CAPI/cpp/API/include/constants.h, CAPI/python/PyAPI/constants.py
=> feat(CAPI): :sparkles: update constants

CAPI/cpp/API/include/constants.h, CAPI/python/PyAPI/constants.py, logic/GameClass/GameObj/Bullet/Bullet.cs, logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/GameObj.cs, logic/GameClass/GameObj/Moveable.cs, logic/GameClass/GameObj/Prop/Gadget.cs, logic/GameClass/GameObj/Prop/Item.cs, logic/GameEngine/MoveEngine.cs, logic/Preparation/Interface/IMoveable.cs
=> fix: :art: deprecate moveReaderWriterLock

CAPI/cpp/API/include/constants.h, CAPI/python/PyAPI/constants.py
=> docs: :memo: edit constants.h

installer/Installer/Model.cs, installer/Installer/ViewModel.cs
=> fix(installer): :rotating_light: remove warnings of installer

CAPI/cpp/API/include/API.h, CAPI/cpp/API/include/Communication.h, CAPI/cpp/API/include/constants.h, CAPI/cpp/API/include/logic.h, CAPI/cpp/API/include/utils.hpp, CAPI/cpp/API/src/API.cpp, CAPI/cpp/API/src/DebugAPI.cpp, CAPI/cpp/API/src/logic.cpp
=> style(CAPI): :art: change int to int32_t

logic/GameClass/GameObj/Map/Generator.cs, logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/ActionManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs
=> fix: 🐛 fix the bug about learning

logic/GameClass/GameObj/Character/Character.cs, logic/Gaming/ActionManager.cs
=> fix: :bug: fix the bug about OpenDoorWay

CAPI/cpp/API/include/constants.h, CAPI/python/PyAPI/constants.py
=> fix(CAPI): :pencil2: fix wrong duration of summon golem

dependency/shell/run.sh
=> hotfix: 🐛 fix python error

logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/AttackManager.cs, logic/Server/GameServer.cs
=> fix: :ambulance: fix the bug about Semaphore when attacking

docs/CAPI接口（cpp）.md, logic/GameClass/GameObj/Character/Character.cs, logic/Gaming/ActionManager.cs, logic/Preparation/Interface/ICharacter.cs, logic/Preparation/Utility/GameData.cs
=> fix: 🚑 fix the wrong PlayerState setting about addicted

logic/Gaming/ActionManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/cmd/spectatorForLadder.cmd
=> fix: 🐛 fix the bug about the wrong setting of RunningStateType

logic/GameClass/GameObj/Character/Character.cs
=> perf: :lock: add a lock for the bgm

logic/Preparation/Interface/ISkill.cs, logic/Server/CopyInfo.cs
=> fix: :bug: try to fix the bug about CD

logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/Game.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs
=> fix: 🚑 fix the bug about SparksNSplash

logic/GameClass/GameObj/Map/Chest.cs, logic/GameClass/GameObj/Map/Door.cs, logic/GameClass/GameObj/Map/Doorway.cs, logic/GameClass/GameObj/Map/MapGameTimer.cs, logic/Gaming/AttackManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Gaming/SkillManager/SkillManager.PassiveSkill.cs, logic/Preparation/Interface/IDoorway.cs, logic/Preparation/Interface/ISkill.cs, logic/Server/CopyInfo.cs, logic/Server/GameServer.cs
=> fix: :bug: change Environment.TickCount64 to Environment.TickCount

logic/Preparation/Interface/ISkill.cs
=> fix: 🐛 fix the Initial value

logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/Character/Character.Student.cs, logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/Map/Chest.cs, logic/GameClass/GameObj/Map/Door.cs, logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/ActionManager.cs, logic/Gaming/Game.cs, logic/Gaming/PropManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Preparation/Interface/ISkill.cs, logic/cmd/spectatorForLadder.cmd
=> perf: 🔒 add locks

dependency/shell/run.sh, logic/Server/ArgumentOption.cs, logic/Server/GameServer.cs, logic/Server/HttpSender.cs
=> chore: add mode

logic/Gaming/ActionManager.cs
=> fix: 🚑 fix the bug about locking when treating

logic/GameClass/GameObj/Bullet/Bullet.Ghost.cs, logic/GameClass/GameObj/Bullet/Bullet.cs, logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/GameObj.cs, logic/GameClass/GameObj/Immovable.cs, logic/GameClass/GameObj/Moveable.cs, logic/GameClass/GameObj/Prop/Gadget.cs, logic/GameClass/GameObj/Prop/Item.cs, logic/GameEngine/MoveEngine.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/Game.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Preparation/Interface/IGameObj.cs, logic/Preparation/Interface/IMoveable.cs, logic/Preparation/Utility/LockedValue.cs, logic/Preparation/Utility/XY.cs
=> refactor: :zap: add the AtomicInt and AtomicBool

logic/Client/MainWindow.xaml.cs, logic/GameClass/GameObj/Bullet/Bullet.Ghost.cs, logic/GameClass/GameObj/Bullet/Bullet.cs, logic/GameClass/GameObj/Character/Character.Skill.cs, logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/GameObj.cs, logic/GameClass/GameObj/Map/Chest.cs, logic/GameClass/GameObj/Map/Door.cs, logic/GameClass/GameObj/Map/Map.cs, logic/GameClass/GameObj/Moveable.cs, logic/GameClass/GameObj/Prop/Gadget.cs, logic/GameClass/GameObj/Prop/Item.cs, logic/GameEngine/MoveEngine.cs, logic/Gaming/ActionManager.cs, logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/Game.cs, logic/Gaming/PropManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Gaming/SkillManager/SkillManager.PassiveSkill.cs, logic/Preparation/Interface/ICharacter.cs, logic/Preparation/Interface/IChest.cs, logic/Preparation/Interface/ISkill.cs, logic/Preparation/Utility/SafeValue.cs, logic/Server/CopyInfo.cs
=> fix: 🐛 fix the SafeValues

logic/Client/MainWindow.xaml.cs, logic/Gaming/ActionManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Preparation/Interface/ISkill.cs, logic/Preparation/Utility/SafeValue.cs, logic/Server/CopyInfo.cs
=> fix: :bug: fix the problem about CD about Trickers and Locking the doors

logic/GameClass/GameObj/Map/Chest.cs, logic/GameClass/GameObj/ObjOfCharacter.cs, logic/Preparation/Utility/SafeValue/Atomic.cs, logic/Preparation/Utility/SafeValue/InTheRange.cs, logic/Preparation/Utility/SafeValue/TimeBased.cs
=> feat(SafeValue): ✨ add some SafeValue

logic/GameClass/GameObj/Character/Character.cs, logic/GameClass/GameObj/Map/Doorway.cs, logic/GameClass/GameObj/Map/Map.cs, logic/Gaming/ActionManager.cs, logic/Preparation/Interface/IDoorway.cs, logic/Preparation/Utility/SafeValue/Atomic.cs, logic/Preparation/Utility/SafeValue/InTheRange.cs, logic/Preparation/Utility/SafeValue/TimeBased.cs, logic/Server/CopyInfo.cs
=> feat: :sparkles: Add the progress TimeBasedProgressAtVariableSpeed

logic/GameClass/GameObj/Map/Map.cs, logic/GameEngine/CollisionChecker.cs, logic/Gaming/AttackManager.cs, logic/Gaming/CharacterManager.cs, logic/Gaming/Game.cs, logic/Gaming/PropManager.cs, logic/Gaming/SkillManager/SkillManager.ActiveSkill.cs, logic/Preparation/Interface/IMap.cs, logic/Preparation/Utility/SafeValue/Atomic.cs, logic/Preparation/Utility/SafeValue/ListLocked.cs, logic/Server/GameServer.cs
=> refactor: 🎨 use the LockedClassList

dependency/shell/run.sh
- [ x ] 您的代码是否能够编译通过？
- [ x ] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI6/pulls) 中是否有与你的贡献功能相同的更改？
- [ x ] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI6/blob/dev/CODE_OF_CONDUCT.md)？
- [ x ] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI6#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  
=> retry command for cpp.

dependency/shell/run.sh
=> Update run.sh: fix /finish payload

CAPI/python/requirements.txt, dependency/shell/run.sh
=> fix(run.sh) and requierments

dependency/shell/run.sh
=> Dev: revise finish payload

dependency/shell/run.sh
=> fix: run.sh retry times
